# SPDX-FileCopyrightText: 2026 <Oliver A. Bramley; Technical University of Denmark>
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# Edit this file to configure a thermochronology simulation. Any ommitted value uses the 
# from the corresponding structure in io/src/inputs.rs.

[setup]
fill_ratio = [0.8]
fill_ratio_error = [0.1]
random_paths = true
