# SPDX-FileCopyrightText: 2026 <Oliver A. Bramley; Technical University of Denmark>
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# Edit this file to configure a simulation. Any omitted value uses the default
# from the corresponding structure in io/src/inputs.rs.

[cube]
uc_h = 1.0e-10
uc_w = 1.0e-10
uc_l = 1.0e-10
x = 7.5e-9
y = 7.5e-9
z = 7.5e-9
density = 5.22e25
hole_count = 1
bandtail_count = 0
periodic = true

[time_temperature]
times = [0.0, 160.0]
temperatures = [0.0, 800.0]
time_unit = "second"
temp_unit = "celsius"

[trap_energies]
e_loc = [1.2]
e_cb = [2.0]
e_loc_sigma = [0.0]
e_cb_sigma = [0.0]
s_frequency_e = [9.0e-10]
s_frequency_g = [9.0e-10]

[initial_conditions]
trap_available = [0]
hole_available = [0]

[localised]
gs_tun = false
es_tun = false
vrh = false
b_gs = [1000000000000]
b_es = [1000000000000]
alpha_gs = [9000000000000]
alpha_es = [9000000000]

[delocalised]
gs_cb = false
es_cb = false
s_gs = [1000000000000]
s_es = [1000000000000]

[filling]
fill = true
d0 = [400.0]
d_dot = [10.0]
dd_unit = "second"

[retrapping]
delocalised = false
localised_gs = false
localised_es = false
filling = true
gaussian = true
cb_hole_to_trap = [1000000.0]
vb_trap_to_hole = [5000000.0]
cb_mu = [0.0000000001]
vb_mu = [0.0000000001]